/*
 * File: pa3Strings.h
 * Description: Header file containing strings that are displayed to the user.
 *
 * XXX DO NOT EDIT THIS FILE
 *
 */

#ifndef PA1_STRINGS_H /* Header guard */
#define PA1_STRINGS_H

/* Error checking in main */
#define	INVALID_ARGS "Incorrect number of arguments.\n"
#define SHORT_USAGE "\n"\
	"Usage ./fpdec {hexString}"\
	"\n\n"

/* Printing individual bits */
#define SIGN_STR "Sign Bit: %u\n"
#define EXP_STR "Unbiased Exponent: %hhd\n"
#define MANTISSA_STR "Mantissa: %lx\n"

/* Printing Decimal for EC2*/
#define DECIMAL_STR "Decimal representation: %f\n"

#endif
