/*
 * File: test.h
 * Author: HanJie Zhan
 * UserId: cs30s120cg
 * Date:07/05/2020
 * Sources of help: none.
 *
 * Description: Header file that provides test macro
 *
 * XXX DO NOT EDIT THIS FILE
 */

#ifndef TEST

#include <stdio.h>

/* Macro to explicity print tests that are run along with colorized result. */
#define TEST(EX) (void)((fprintf( stderr, "(%s:%d) %s:", __FILE__, __LINE__,\
				                 #EX)) && ((EX && fprintf(stderr, "\t\x1b[32mPASSED\x1b[0m\n"))\
						                  || (fprintf(stderr, "\t\x1b[31mFAILED\x1b[0m\n")) ))

#endif
